services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/express_api_v1
      - /usr/express_api_v1/node_modules
    develop:
      watch:
        - action: rebuild
          path: ./src/**/*
    depends_on:
      - mongodb
      - redis
      - postgres
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: test12345
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data
    restart: unless-stopped

  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - mongodb
      - redis
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
  postgres_data:
  
